### Multiple Linear Regression

### Assumptions for Multiple Linear Regression:

### Implementaton

In [1]:
import numpy as np  
import matplotlib.pyplot as plt 
import pandas as pd  

In [2]:
import seaborn as sns
df=sns.load_dataset('')

In [23]:
sns.get_dataset_names()

<function seaborn.utils.get_dataset_names()>

In [3]:
df.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [4]:
X=df.drop('species',axis=1)
y=df.species

In [13]:
X[0:5]

array([[-0.90068117,  1.01900435, -1.34022653, -1.3154443 ],
       [-1.14301691, -0.13197948, -1.34022653, -1.3154443 ],
       [-1.38535265,  0.32841405, -1.39706395, -1.3154443 ],
       [-1.50652052,  0.09821729, -1.2833891 , -1.3154443 ],
       [-1.02184904,  1.24920112, -1.34022653, -1.3154443 ]])

In [5]:
from sklearn.preprocessing import StandardScaler
ss=StandardScaler()

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [7]:
X=ss.fit_transform(X)

In [8]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)

In [14]:
y[0:5]

array([0, 0, 0, 0, 0])

In [16]:
from sklearn.linear_model import LinearRegression
regr=LinearRegression()

In [10]:
df.head(2)

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa

In [17]:
regr.fit(X_train,y_train)

LinearRegression()

In [18]:
regr.predict(X_test)

array([ 1.23071715, -0.04010441,  2.21970287,  1.34966889,  1.28429336,
        0.02248402,  1.05726124,  1.82403704,  1.36824643,  1.06766437,
        1.70031437, -0.07357413, -0.15562919, -0.06569402, -0.02128628,
        1.39659966,  2.00022876,  1.04812731,  1.28102792,  1.97283506,
        0.03184612,  1.59830192,  0.09450931,  1.91807547,  1.83296682,
        1.87877315,  1.78781234,  2.03362373,  0.03594506,  0.02619043])

In [21]:
X_test[0:1]

array([[ 0.31099753, -0.59237301,  0.53540856,  0.00087755]])

In [22]:
regr.predict(X_test[0:1])

array([1.23071715])