### Stock price Prediction

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
import sys
sys.version

'3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]'

In [5]:
df.drop('Unnamed: 0',axis=1, inplace=True)

In [6]:
df.head(2)

count  hate_speech  offensive_language  neither  class  \
0      3            0                   0        3      2   
1      3            0                   3        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...

In [7]:
df['hate_speech'].unique()

array([0, 1, 2, 3, 4, 6, 5, 7], dtype=int64)

In [8]:
df['class'].unique()

array([2, 1, 0], dtype=int64)

In [9]:
df['offensive_language'].unique()

array([0, 3, 2, 6, 1, 7, 5, 4, 8, 9], dtype=int64)

In [10]:
df['count'].unique()

array([3, 6, 9, 4, 7], dtype=int64)