### Introduction to NumPy

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
# when was numpy created?

In [3]:
# Why is NumPy Faster Than Lists?

In [4]:
# Which Language is NumPy written in?

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [7]:
# check version
print(np.__version__)

1.20.3


In [8]:
# Use a tuple to create a NumPy array:
arr = np.array((1, 2, 3, 4, 5))

print(arr)

[1 2 3 4 5]


In [9]:
# what is Dimensions in Arrays??

In [10]:
# what is a 0-D Arrays

In [11]:
# Create a 0-D array with value 42

arr=np.array(31)
print(arr)

31


In [12]:
# 1-D Arrays

In [13]:
# what is a 2-D Arrays?

In [14]:
# Create a 2-D array containing two arrays with the values 1,2,3 and 4,5,6:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [15]:
# what is a 3-D arrays??

In [16]:
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print('Dimension of the array is:',arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension of the array is: 3


In [17]:
# how many dimension can a numpy array have?

In [18]:
# define an array with 6 dimension
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.ndim)

[[[[[1 2 3 4]]]]]
5


### Indexing of arrays

In [19]:
# Get third and fourth elements from the following array and add them.

arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [20]:
# Access the element on the first row, second column:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[0,1]

2

In [21]:
# get 5
arr[0,4]

5

In [22]:
# get 10
arr[1,4]

10

In [23]:
# Access 3-D Arrays
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
# Access the third element of the second array of the first array:
arr[0,1,2]

6

In [24]:
# access 10
arr[1,1,0]

10

In [25]:
# Print the last element from the 2nd dim:

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr[1,-1]

10

In [26]:
# what is Slicing arrays??

In [27]:
# Get 3rd last to 1st last
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[-3:-1]

array([5, 6])

In [28]:
# step
arr = np.array([1, 2, 3, 4, 5, 6, 7])
arr[0:6:2]

array([1, 3, 5])

In [29]:
# last index is not included, but we can extend last index by one to print whole element, see later code block
arr[0:6]

array([1, 2, 3, 4, 5, 6])

In [30]:
arr[0:7]

array([1, 2, 3, 4, 5, 6, 7])

In [31]:
arr[0:-1]

array([1, 2, 3, 4, 5, 6])

### Slicing 2-D Arrays

In [32]:
# consider the below arr, it contains element in both array at index 0 and 1
arr=np.array([[1,2,3,4,5,6,7],[11,14,15,12,35,2,15]])
arr.shape

(2, 7)

In [33]:
# lets increase element of array at index 1 by 2
arr=np.array([[1,2,3,4,5,6,7],[11,14,15,12,35,2,15,16,17]])
arr.shape

(2,)

In [34]:
print(arr.ndim)

1


In [35]:
# acess elements of this 2d array, print 1,2,3,4
arr=np.array([[1,2,3,4,5,6,7],[11,14,15,12,35,2,15]])
arr[0,0:4]

array([1, 2, 3, 4])

In [36]:
# get 11,14
arr[1,0:2]

array([11, 14])

In [37]:
# From both elements, return index 2: when we access only 1 element from both arrays, it return 1D array

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2,2]

array([3, 8])

In [38]:
# From both elements, slice index 1 to index 4. when we access only many elements from both arrays, it return 2D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr[0:2,1:5]

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

### NumPy Data Types

In [39]:
# how will u check data type of a numpy array
arr=np.array([1,2,3,4])
print(arr.dtype)

int32


In [40]:
# if we give true as an element in np array it will be printed as 1
arr=np.array([1,2,3,4,True])
print(arr)

[1 2 3 4 1]


In [41]:
arr=np.array([1,2,False,False,True])
print(arr)

[1 2 0 0 1]


In [42]:
arr=np.array([1.0,'vivek',2,3,4,True])
print(arr)

['1.0' 'vivek' '2' '3' '4' 'True']


In [43]:
# cant create numpy array with another sequece as element
arr=np.array([1,'baba',1j,4.5, 2,3,4,True,[1,2,3],{1,2,'a'}])
print(arr)

[1 'baba' 1j 4.5 2 3 4 True list([1, 2, 3]) {'a', 1, 2}]


In [44]:
arr2=np.array([1,2,3,[4,5,6]])
print(arr2)

[1 2 3 list([4, 5, 6])]


In [45]:
arr2=np.array([1,2,3,[4,5,6]],dtype='i')
print(arr2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [46]:
arr2=np.array([1,2,3,[4,5,6]],dtype='S')
print(arr2)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.

In [47]:
arr3 = np.array(['apple', 'banana', 'cherry'])
print(arr.dtype)

arr4=np.array(['baba','vivek','veer'])
print(arr4)

object
['baba' 'vivek' 'veer']


In [48]:
# create anarray with define data type
arr=np.array([1,2,3,4],dtype='f')
print(arr)

[1. 2. 3. 4.]


In [49]:
# as string data type
arr=np.array([1,2,3,4],dtype='S')
print(arr)

[b'1' b'2' b'3' b'4']


In [50]:
# change datatype to bool and see what happens
arr=np.array([1,2,3,4],dtype='bool')
print(arr)

[ True  True  True  True]


In [51]:
arr = np.array([1, 2, 3, 4], dtype='c')
print(arr)

[b'1' b'2' b'3' b'4']


In [52]:
# A non integer string like 'a' can not be converted to integer (will raise an error):

arr = np.array(['a', '2', '3'], dtype='i')

ValueError: invalid literal for int() with base 10: 'a'

###  changing data type of an existing array

In [53]:
arr=np.array([1,2,3,4],dtype='i')
arr.dtype

dtype('int32')

In [54]:
arr2=arr.astype('f')
print(arr2)

[1. 2. 3. 4.]


In [55]:
# float to integer
arr = np.array([1.1, 2.1, 3.1])
arr2=arr.astype('int64')
print(arr2)
print(arr2.dtype)

[1 2 3]
int64


In [56]:
# Change data type from integer to boolean:

arr=np.array([1,2,3,4])
arr2=arr.astype('bool')
print(arr2)

[ True  True  True  True]


### Copy vs View

In [57]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0]=6

# original array will not change
print(arr)

[1 2 3 4 5]


In [58]:
# view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

# both will change
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [59]:
# Check if Array Owns it's Data

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [60]:
# what is Shape of an Array?

In [61]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [62]:
# Create an array with 5 dimensions 

arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 2 3 4]]]]]
(1, 1, 1, 1, 4)


### NumPy Array Reshaping

In [63]:
# Convert the following 1-D array with 12 elements into a 2-D array.

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
arr.reshape(2,6)
print(arr)
# reshaping does not change the original array, since reshaping can result in a diffrent array hence new array is returned

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [64]:
arr2=arr.reshape(2,6)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [65]:
# Reshape From 1-D to 3-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2) # last parameter indicate elements in innner most structure
newarr

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [66]:
newarr = arr.reshape(2, 2, 3) # 2 columns, 2 rows, 3 elements each
newarr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [67]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2=arr.reshape(2,4)
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [68]:
# Unknown Dimension

In [69]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr2=arr.reshape(2,2,-1)
print(arr2)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [70]:
# Flattening the arrays

In [71]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr2=arr.reshape(-1)
print(arr2)

[1 2 3 4 5 6]


In [72]:
print(arr)

[[1 2 3]
 [4 5 6]]


### NumPy Array Iteration

In [73]:
arr = np.array([1, 2, 3])

for x in arr:
  print(x)

1
2
3


In [74]:
# Iterating 2-D Arrays

In [75]:
# Iterate on the elements of the following 2-D array:

arr = np.array([[1, 2, 3], [4, 5, 6]])
for x in arr:
    print(x)

[1 2 3]
[4 5 6]


In [76]:
for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


In [77]:
# Iterating 3-D Arrays

In [78]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
for x in arr:
    print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [79]:
for x in arr:
  for y in x:
    for z in y:
      print(z, end=' ')

1 2 3 4 5 6 7 8 9 10 11 12 

In [80]:
# Iterating Arrays Using nditer()

In [81]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arr):
    print(x,end=' ')

1 2 3 4 5 6 7 8 

In [82]:
# Iterating Array With Different Data Types

In [83]:
arr = np.array([1, 2, 3])
for x in np.nditer(arr,flags=['buffered'], op_dtypes=['S']):
    print(x)

b'1'
b'2'
b'3'


In [84]:
# Iterating With Different Step Size
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Iterate through every scalar element of the 2D array skipping 1 element:

for x in np.nditer(arr[:,::2]):
    print(x)

1
3
5
7


In [85]:
# iterate every 3rd element
for x in np.nditer(arr[:,::3]):
    print(x)

1
4
5
8


In [86]:
# every 4th element iteration
for x in np.nditer(arr[:,::4]):
    print(x)

1
5


In [87]:
# Sometimes we require corresponding index of element while iterating, the ndenumerate() method can be used for those usecases.

arr=np.array([[1,2,3,4],[5,6,7,8]])
for x,y in np.ndenumerate(arr):
    print(x,y)  

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [88]:
for (i,j) in np.ndenumerate(arr):
    print(i,j)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


In [89]:
# by skipping some elements
for (i,j) in np.ndenumerate(arr[:,::2]):
    print(i,j)

(0, 0) 1
(0, 1) 3
(1, 0) 5
(1, 1) 7
