### NumPy Joining Array

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2),axis=0,dtype=None)
print(arr)

[1 2 3 4 5 6]


In [3]:
# mention dtype as string
arr = np.concatenate((arr1, arr2),axis=0,dtype='S')
print(arr)

[b'1' b'2' b'3' b'4' b'5' b'6']


In [4]:
# concat along axis=1

try:
    arr1 = np.array([1, 2, 3])
    arr2 = np.array([4, 5, 6])
    arr = np.concatenate((arr1, arr2),axis=1,dtype=None)
    print(arr)
except:
    print('AxisError: axis 1 is out of bounds for array of dimension 1')
# will give AxisError: axis 1 is out of bounds for array of dimension 1

AxisError: axis 1 is out of bounds for array of dimension 1


In [5]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [6]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=0)

print(arr)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [7]:
# stackig 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
# stacking along rows
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [20]:
# stacking along col 
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


### NumPy Splitting Array

In [21]:
# split the array in 3 parts

arr = np.array([1, 2, 3, 4, 5, 6])
arr2=np.array_split(arr,3)
print(arr2)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [22]:
# into two parts
arr2=np.array_split(arr,2)
print(arr2)

[array([1, 2, 3]), array([4, 5, 6])]


In [23]:
# If the array has less elements than required, it will adjust from the end accordingly.

arr3=np.array_split(arr,4)
arr3

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [27]:
# Splitting 2-D Arrays
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.array_split(arr, 3)
print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [29]:
# In addition, you can specify which axis you want to do the split around.

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9], 
                [10, 11, 12], 
                [13, 14, 15], 
                [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [30]:
# likewise the is hsplit and vsplit

### NumPy Searching Arrays

In [32]:
# Find the indexes where the value is 4:

arr=np.array([1,2,3,4,5])
print(np.where(arr==4))

(array([3], dtype=int64),)


In [33]:
# find multiple indexes where arr is 4
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print(np.where(arr==4)) 

(array([3, 5, 6], dtype=int64),)


In [34]:
# Find the indexes where the values are even:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
print(np.where(arr%2==0)) 

(array([1, 3, 5, 6], dtype=int64),)


In [35]:
# Find the indexes where the values are odd:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.where(arr%2==1))

(array([0, 2, 4, 6, 8], dtype=int64),)


In [36]:
# # Search Sorted

In [37]:
a=np.array([1,2,3,5,8,9])
print(np.searchsorted(a, 10))

6


In [38]:
a=np.array([1,2,3,4,5,6,8,9])
print(np.searchsorted(a, 7))

6


In [39]:
# Search From the Right Side

arr = np.array([6, 7, 8, 9])
x = np.searchsorted(arr, 7, side='right')
print(x)

2


In [40]:
# Find the indexes where the values 2, 4, and 6 should be inserted:
a=np.array([1,3,5,7])
print(np.searchsorted(a, [2,4,6]))

[1 2 3]


### NumPy Sorting Arrays

In [41]:
arr = np.array([3, 2, 0, 1])
np.sort(arr)

array([0, 1, 2, 3])

In [42]:
arr=np.array([2j,3j,1.5j])
np.sort_complex(arr)

array([0.+1.5j, 0.+2.j , 0.+3.j ])

In [43]:
# You can also sort arrays of strings, or any other data type:
arr=np.array(['vivek','baba','bablu','vicky sen','veer','veeru','vivekanand','veersen'])
np.sort(arr)

array(['baba', 'bablu', 'veer', 'veersen', 'veeru', 'vicky sen', 'vivek',
       'vivekanand'], dtype='<U10')

In [44]:
arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


In [45]:
# If you use the sort() method on a 2-D array, both arrays will be sorted:

arr=np.array([[1,6,2,4,7,3,2,6,2],[5,3,3,237,73,2,72,7,3]])
np.sort(arr)

array([[  1,   2,   2,   2,   3,   4,   6,   6,   7],
       [  2,   3,   3,   3,   5,   7,  72,  73, 237]])

### NumPy Filter Array

In [51]:
# filter and return only even numbers

a=np.array([1,2,3,4,5,6])
a2=[]
for i in a:
    if i%2==0:
        a2.append(True)
    else:
        a2.append(False)
print(a[a2])

[2 4 6]


In [48]:
a2

[True, True, True]

In [52]:
print(a[a2])

[2 4 6]


In [53]:
arr = np.array([41, 42, 43, 44])
x = [True, False, True, False]
newarr = arr[x]
print(newarr)

[41 43]


In [57]:
# return element greater than 10
a=[1,2,5,3,2,2,41,33,6,7,84,2,73,8,7,6,5,6,64,656,5656,5,4,4,3,4,343,3049,0]
filtr=[]
for x in a:
    if x > 10:
        filtr.append(x)
print(filtr)

[41, 33, 84, 73, 64, 656, 5656, 343, 3049]


In [59]:
# Creating Filter Directly From Array

a=np.array([1,2,5,3,2,2,41,33,6,7,84,2,73,8,7,6,5,6,64,656,5656,5,4,4,3,4,343,3049,0])
fltr=a>10
a[fltr]

array([  41,   33,   84,   73,   64,  656, 5656,  343, 3049])