### Numpy Ufunc

In [ ]:
# What is Vectorization?

In [5]:
# adding two elements without ufunc
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = []

for i, j in zip(x,y):
    z.append(i+j)
print(z)

[5, 7, 9, 11]


In [7]:
# what does zip does
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = zip(x,y)
print(z)

In [8]:
# With ufunc, we can use the add() function:

import numpy as np
np.add(x,y)

array([ 5,  7,  9, 11])

In [9]:
# Create Your Own ufunc

def myaddition(x,y):
    return x+y
myaddition(10,10)

20

In [13]:
def myaddition(x,y):
    print(np.add(x+y))
myaddition([1, 2, 3, 4],[5,6,7,8,9])

ValueError: invalid number of arguments

In [14]:
# check if a function is ufunc
print(type(np.add))

<class 'numpy.ufunc'>


In [16]:
# Use an if statement to check if the function is a ufunc or not:

if type(np.add)==np.ufunc:
    print('ufunc')
else:
    print('not ufunc')

ufunc


### Simple Arithmetic

In [19]:
# addition of two arrays
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(arr1+arr2)

# or

print(np.add(arr1,arr2))

[30 32 34 36 38 40]
[30 32 34 36 38 40]


In [20]:
# substraction of two arrays
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

print(arr1-arr2)

# or

print(np.subtract(arr1,arr2))

[-10 -10 -10 -10 -10 -10]
[-10 -10 -10 -10 -10 -10]


In [21]:
# multiply
np.multiply(arr1, arr2)

array([200, 231, 264, 299, 336, 375])

In [22]:
# or 
arr1*arr2

array([200, 231, 264, 299, 336, 375])

In [23]:
# division
np.divide(arr1, arr2)

array([0.5       , 0.52380952, 0.54545455, 0.56521739, 0.58333333,
       0.6       ])

In [24]:
# or
arr1/arr2

array([0.5       , 0.52380952, 0.54545455, 0.56521739, 0.58333333,
       0.6       ])

In [25]:
# power
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
np.power(arr1,arr2)

array([  1,  32, 729], dtype=int32)

In [26]:
# OR
pow(arr1,arr2)

array([  1,  32, 729], dtype=int32)

In [27]:
# remainder, we use modlus funciton for this

np.mod(arr1,arr2)

array([1, 2, 3], dtype=int32)

In [28]:
# OR
arr1%arr2

array([1, 2, 3], dtype=int32)

In [29]:
# Return the quotient and mod:

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

np.divmod(arr1, arr2)

(array([ 3,  2,  3,  5, 25,  1], dtype=int32),
 array([ 1,  6,  3,  0,  0, 27], dtype=int32))

In [30]:
# Absolute Values

In [31]:
# absolute value of a list using ufunc
arr = np.array([-1, -2, 1, 2, 3, -4])
np.absolute(arr)

array([1, 2, 1, 2, 3, 4])

In [32]:
# using inbuilt python function
abs(arr)

array([1, 2, 1, 2, 3, 4])

### Rouding Decimal

In [34]:
# truncaton, removes decimal part and returns floating number closest to zero

In [33]:
np.trunc([-3.1666, 3.6667])

array([-3.,  3.])

In [35]:
np.fix([-3.1666, 3.6667])

array([-3.,  3.])

In [36]:
# Rounding

In [37]:
# Round off 3.1666 to 2 decimal places:

np.around(1.24453,2)

1.24

In [39]:
np.around(1.24453,3)

1.245

In [42]:
np.around([i for i in range(10)])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
# rounding a list
np.around([1.2,3.6,5.9])

array([1., 4., 6.])

In [38]:
# without second parameter it rounds up to 1 decimal points
np.around(1.24453)

1.0

In [40]:
# The floor() function rounds off decimal to nearest lower integer.

np.floor(3.221994)

3.0

In [44]:
np.floor(3.221994)

3.0

In [47]:
# np.ceil
np.ceil([-3.1666, 3.6667])

array([-3.,  4.])

### NumPy Logs

In [48]:
# Log at Base 2

In [49]:
# Find log at base 2 of all elements of following array:

arr=np.arange(10)
np.log2(arr)

C:\Users\iamvi\AppData\Local\Temp/ipykernel_14064/1026529400.py:4: RuntimeWarning: divide by zero encountered in log2
  np.log2(arr)


array([      -inf, 0.        , 1.        , 1.5849625 , 2.        ,
       2.32192809, 2.5849625 , 2.80735492, 3.        , 3.169925  ])

In [50]:
np.log2(10)

3.321928094887362

In [51]:
np.log2((10,20,30))

array([3.32192809, 4.32192809, 4.9068906 ])

In [52]:
# log2 of a coplex no, can also be calculate becuase finally its a real number
np.log2(10j)

(3.3219280948873626+2.2661800709135966j)

In [53]:
# log2 of a negative number, will return nan
np.log2(-10)

C:\Users\iamvi\AppData\Local\Temp/ipykernel_14064/4271057577.py:2: RuntimeWarning: invalid value encountered in log2
  np.log2(-10)


nan

In [54]:
# log at base 10

np.log10(10)

1.0

In [55]:
np.log10(100)

2.0

In [56]:
np.log10([10,20,220])

array([1.        , 1.30103   , 2.34242268])

In [58]:
np.log10(np.arange(300,600,100))

array([2.47712125, 2.60205999, 2.69897   ])

In [59]:
# Natural Log, or Log at Base e

In [60]:
arr = np.arange(1, 10)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]


In [61]:
np.log(10)

2.302585092994046

In [62]:
np.log(100)

4.605170185988092

In [63]:
np.log(-100)

C:\Users\iamvi\AppData\Local\Temp/ipykernel_14064/60392587.py:1: RuntimeWarning: invalid value encountered in log
  np.log(-100)


nan

#### Log at Any Base

In [64]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052


In [65]:
nplog(200,15)

1.9565063322650205

In [66]:
nplog(225,15)

2.0

In [67]:
# NumPy Summations

In [68]:
# What is the difference between summation and addition?

In [69]:
# add
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
np.add(arr1, arr2)

array([2, 4, 6])

In [71]:
# sum
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])
np.sum([arr1, arr2])

12

In [73]:
# over axis 1
arr1 = np.array([1, 2, 3])
arr2 = np.array([1, 2, 3])

np.sum([arr1, arr2], axis=1)

array([6, 6])

In [74]:
# cumsum
arr = np.array([1, 2, 3])
np.cumsum(arr)

array([1, 3, 6], dtype=int32)

### NumPy Products

In [76]:
# we need to pass every element in a list to find the product using numpy.prod()
np.prod([3,4])

12

In [77]:
np.prod([1,2,3,4,5])

120

In [79]:
try:
    np.prod([4],[5])
except:
    print("TypeError: 'list' object cannot be interpreted as an integer")

TypeError: 'list' object cannot be interpreted as an integer


In [80]:
# lets chekc if there is any built in function to find product

In [81]:
a1=[1,2,3,4]
a2=[5,6,7,8]
a1*a2

TypeError: can't multiply sequence by non-int of type 'list'

In [82]:
# it said a sequence can't be multiplied with a non-int type data, let give an int

a1=[1,2,3,4]
a2=5
a1*a2
# repeats all the elements 5 times

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [87]:
# product over an axis
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])
np.prod([arr1, arr2], axis=1)

array([  24, 1680])

In [88]:
# cumulative prod
arr = np.array([5, 6, 7, 8])
np.cumprod(arr)

array([   5,   30,  210, 1680], dtype=int32)

In [89]:
arr=np.array([1,2,3,4])
np.diff(arr)

array([1, 1, 1])

In [91]:
# changing last element
arr=np.array([1,2,3,5])
np.diff(arr)

array([1, 1, 2])

In [92]:
# We can perform this operation repeatedly by giving parameter n.

arr=np.array([1,2,3,4])
np.diff(arr,2) # two times

array([0, 0])

### LCM

In [93]:
np.lcm(10,20)

20

In [94]:
np.lcm(1,5)

5

In [95]:
arr = np.array([3, 6, 9])
np.lcm.reduce(arr)

18

In [96]:
arr=np.array((5,10,20,15,80))
np.lcm.reduce(arr)

240

In [97]:
arr = np.arange(1, 11)
np.lcm.reduce(arr)

2520

### NumPy GCD Greatest Common Denominator

In [100]:
np.gcd(2,4)

2

In [101]:
# Find the GCD for all of the numbers in following array:

arr = np.array([20, 8, 32, 36, 16])
np.gcd.reduce(arr)

4

In [102]:
np.gcd.reduce((2,4,6,7,8,9))

1

#### ufunc trigonometric

In [103]:
np.sin(np.pi/2)

1.0

In [104]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
np.sin(arr)

array([1.        , 0.8660254 , 0.70710678, 0.58778525])

In [105]:
# Convert all of the values in following array arr to radians:
arr = np.array([90, 180, 270, 360])
np.deg2rad(arr)

array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

In [106]:
# Radians to Degrees
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])
np.rad2deg(arr)

array([ 90., 180., 270., 360.])

In [107]:
# Find the angle of 1.0:

np.arcsin(1.0)

1.5707963267948966

In [108]:
# Find the angle for all of the sine values in the array

arr = np.array([1, -1, 0.1])
np.arcsin(arr)

array([ 1.57079633, -1.57079633,  0.10016742])

In [109]:
# Find the hypotenues for 4 base and 3 perpendicular:

base = 3
perp = 4
np.hypot(base, perp)

5.0

#### NumPy Hyperbolic Functions

In [110]:
np.sinh(np.pi/2)

2.3012989023072947

In [111]:
arr = np.array([np.pi/2, np.pi/3, np.pi/4, np.pi/5])
np.cosh(arr)

array([2.50917848, 1.60028686, 1.32460909, 1.20397209])

#### NumPy Set Operations

In [112]:
# What is a Set

In [113]:
# Convert following array with repeated elements to a set:

arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
np.unique(arr)

array([1, 2, 3, 4, 5, 6, 7])

In [114]:
# using set constructor
arr = np.array([1, 1, 1, 2, 3, 4, 5, 5, 6, 7])
set(arr)

{1, 2, 3, 4, 5, 6, 7}

In [116]:
# Find union of the following two set arrays:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

np.union1d(arr1, arr2)

# repeated element will be ignored

array([1, 2, 3, 4, 5, 6])

In [117]:
# Find intersection of the following two set arrays:

arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([3, 4, 5, 6])

np.intersect1d(arr1, arr2, assume_unique=True)

array([3, 4])