In [9]:
import numpy as np

In [10]:
from numpy import random

In [11]:
rnd=random.binomial(2,0.5,size=(4,6))

In [12]:
rnd

array([[1, 2, 1, 0, 1, 1],
       [1, 1, 2, 0, 1, 1],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1]])

In [17]:
type(rnd)

numpy.ndarray

In [18]:
rnd.shape

(4, 6)

In [13]:
import seaborn as sns

In [26]:
# 
random.random()

0.8030374567330125

In [27]:
random.random(2)

array([0.72784587, 0.62082373])

In [30]:
import pandas as pd

In [33]:
rnd=random.random((2,3))

In [34]:
rnd

array([[0.28487404, 0.77804525, 0.13673978],
       [0.22735374, 0.18740822, 0.79558354]])

In [35]:
rnd

array([[0.28487404, 0.77804525, 0.13673978],
       [0.22735374, 0.18740822, 0.79558354]])

In [36]:
pd.DataFrame(rnd)

0         1         2
0  0.284874  0.778045  0.136740
1  0.227354  0.187408  0.795584